In [1]:
from sklearn.datasets import fetch_20newsgroups
newsgroups_train = fetch_20newsgroups(subset='train')

from pprint import pprint
pprint(list(newsgroups_train.target_names))


['alt.atheism',
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'comp.sys.ibm.pc.hardware',
 'comp.sys.mac.hardware',
 'comp.windows.x',
 'misc.forsale',
 'rec.autos',
 'rec.motorcycles',
 'rec.sport.baseball',
 'rec.sport.hockey',
 'sci.crypt',
 'sci.electronics',
 'sci.med',
 'sci.space',
 'soc.religion.christian',
 'talk.politics.guns',
 'talk.politics.mideast',
 'talk.politics.misc',
 'talk.religion.misc']


In [2]:
newsgroups_train.filenames.shape



(11314,)

In [3]:
newsgroups_train.target.shape



(11314,)

In [4]:
newsgroups_train.target[:10]

array([ 7,  4,  4,  1, 14, 16, 13,  3,  2,  4])

In [5]:
cats = ['alt.atheism', 'sci.space']
newsgroups_train = fetch_20newsgroups(subset='train', categories=cats)

list(newsgroups_train.target_names)

newsgroups_train.filenames.shape

newsgroups_train.target.shape

newsgroups_train.target[:10]


array([0, 1, 1, 1, 0, 1, 1, 0, 0, 0], dtype=int64)

In [6]:
cats = ['alt.atheism', 'sci.space']
newsgroups_train = fetch_20newsgroups(subset='train', categories=cats)

list(newsgroups_train.target_names)

newsgroups_train.filenames.shape

newsgroups_train.target.shape

newsgroups_train.target[:10]

array([0, 1, 1, 1, 0, 1, 1, 0, 0, 0], dtype=int64)

In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer
categories = ['alt.atheism', 'talk.religion.misc',
              'comp.graphics', 'sci.space']
newsgroups_train = fetch_20newsgroups(subset='train',
                                      categories=categories)
vectorizer = TfidfVectorizer()
vectors = vectorizer.fit_transform(newsgroups_train.data)
vectors.shape
print(vectors.shape)

print(vectors)

(2034, 34118)
  (0, 70)	0.10710818409513174
  (0, 2963)	0.09472446806841893
  (0, 13773)	0.054648651174850946
  (0, 12338)	0.09774026455804982
  (0, 31999)	0.06360491296754224
  (0, 2224)	0.0922603829190838
  (0, 2918)	0.08678050128011777
  (0, 2126)	0.11661288826747816
  (0, 2476)	0.1346278818996714
  (0, 30436)	0.0680446622059539
  (0, 25223)	0.0808091090732652
  (0, 22657)	0.029855879001418763
  (0, 11075)	0.05478870477075606
  (0, 18973)	0.05759496138771589
  (0, 12867)	0.06207326999910133
  (0, 32755)	0.07050874735528904
  (0, 12562)	0.050081322013322396
  (0, 27181)	0.10710818409513174
  (0, 28753)	0.06136797688041764
  (0, 6129)	0.04763380958348832
  (0, 8288)	0.10710818409513174
  (0, 14274)	0.018039928930651487
  (0, 14330)	0.11889848310080865
  (0, 15885)	0.020880502242459024
  (0, 27117)	0.06387795358848057
  :	:
  (2033, 1516)	0.046156243494250744
  (2033, 22951)	0.014452191184297277
  (2033, 25801)	0.017796182688296136
  (2033, 22657)	0.030619667572787022
  (2033, 14274)	0

In [8]:
vectors.nnz / float(vectors.shape[1])


9.479834691365262

In [9]:
vectors.nnz 

323433

In [10]:
vectors.nnz / float(vectors.shape[0])

159.0132743362832

In [11]:
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
newsgroups_test = fetch_20newsgroups(subset='test',
                                     categories=categories)
vectors_test = vectorizer.transform(newsgroups_test.data)
clf = MultinomialNB(alpha=.01)
clf.fit(vectors, newsgroups_train.target)
pred = clf.predict(vectors_test)
metrics.f1_score(newsgroups_test.target, pred, average='macro')

0.8821359240272957

In [15]:
import numpy as np
def show_top10(classifier, vectorizer, categories):
    feature_names = np.asarray(vectorizer.get_feature_names_out())
    for i, category in enumerate(categories):
        top10 = np.argsort(classifier.coef_[i])[-10:]
        print("%s: %s" % (category, " ".join(feature_names[top10])))

show_top10(clf, vectorizer, newsgroups_train.target_names)


AttributeError: 'MultinomialNB' object has no attribute 'coef_'

In [14]:
def show_top10(classifier, vectorizer, categories):
    feature_names = np.asarray(vectorizer.get_feature_names_out())
    for i, category in enumerate(categories):
        top10 = np.argsort(classifier.feature_log_prob_[i])[-10:]
        print("%s: %s" % (category, " ".join(feature_names[top10])))

show_top10(clf, vectorizer, newsgroups_train.target_names)


alt.atheism: edu it and in you that is of to the
comp.graphics: edu in graphics it is for and of to the
sci.space: edu it that is in and space to of the
talk.religion.misc: not it you in is that and to of the


In [13]:
import numpy as np

def show_top10(classifier, vectorizer, categories):
    feature_names = np.asarray(vectorizer.get_feature_names_out())
    for i, category in enumerate(categories):
        top10 = np.argsort(classifier.coef_[i])[-10:]
        print("%s: %s" % (category, " ".join(feature_names[top10])))

# assuming clf, vectorizer, and newsgroups_train are defined and properly set up
show_top10(clf, vectorizer, newsgroups_train.target_names)


AttributeError: 'MultinomialNB' object has no attribute 'coef_'

In [ ]:
import sklearn
print(sklearn.__version__)


In [ ]:
feature_names = np.asarray(vectorizer.get_feature_names_out())


In [ ]:
pip install --upgrade --user scikit-learn


In [ ]:
pip install --upgrade --user scikit-learn


In [ ]:
clf.fit(X_train, y_train)


In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.datasets import fetch_20newsgroups
from sklearn.model_selection import train_test_split

# Load dataset
newsgroups = fetch_20newsgroups(subset='all')

# Split into training and testing sets
X_train_raw, X_test_raw, y_train, y_test = train_test_split(newsgroups.data, newsgroups.target, test_size=0.25, random_state=42)

# Transform text data into vectors
vectorizer = TfidfVectorizer()
X_train = vectorizer.fit_transform(X_train_raw)
X_test = vectorizer.transform(X_test_raw)

# Train the classifier
clf = MultinomialNB()
clf.fit(X_train, y_train)


MultinomialNB()

In [17]:
newsgroups_test = fetch_20newsgroups(subset='test',
                                     remove=('headers', 'footers', 'quotes'),
                                     categories=categories)
vectors_test = vectorizer.transform(newsgroups_test.data)
pred = clf.predict(vectors_test)
metrics.f1_score(pred, newsgroups_test.target, average='macro')


0.06328805099101174

In [18]:
newsgroups_train = fetch_20newsgroups(subset='train',
                                      remove=('headers', 'footers', 'quotes'),
                                      categories=categories)
vectors = vectorizer.fit_transform(newsgroups_train.data)
clf = MultinomialNB(alpha=.01)
clf.fit(vectors, newsgroups_train.target)
vectors_test = vectorizer.transform(newsgroups_test.data)
pred = clf.predict(vectors_test)
metrics.f1_score(newsgroups_test.target, pred, average='macro

SyntaxError: unterminated string literal (detected at line 9) (2692126540.py, line 9)